#!/bin/bash
#######
# Create virtual environment for python application
# All dependencies for the application should be added
######
VIRTUAL_ENV="venv_athlete"
if [ -d "$VIRTUAL_ENV" ]; then
	echo "Remove existing virtual environment"
  	rm -rf "$VIRTUAL_ENV"
fi
echo "Creating $VIRTUAL_ENV ....."
virtualenv "$VIRTUAL_ENV"
source "$VIRTUAL_ENV"/bin/activate
pip install tabulate
echo "Completed setup"
echo "Executing Application"
echo "           "
python athlets.py
